Make symmetric key encryptable
N.B.! This is a not well-though-out change, just needed to make the thing work. The issue was:
```
[2021-09-13 11:12:44,763] ERROR [RemoteLogManager=0 partition=TopicIdPartition{topicId=aFu8kyNMQ1aBsPgE5Dsk2w, topicPartition=my-topic-0}] Error occurred while copying log segments of partition: TopicIdPartition{topicId=aFu8kyNMQ1aBsPgE5Dsk2w, topicPartition=my-topic-0} (kafka.log.remote.RemoteLogManager$RLMTask)
java.lang.ArrayIndexOutOfBoundsException: too much data for RSA block
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at io.aiven.kafka.tiered.storage.commons.security.EncryptionKeyProvider.encryptKey(EncryptionKeyProvider.java:77)
	at io.aiven.kafka.tiered.storage.commons.metadata.EncryptedRepositoryMetadata.serialize(EncryptedRepositoryMetadata.java:44)
	at io.aiven.kafka.tiered.storage.s3.S3EncryptionKeyProvider.createOrRestoreEncryptionKey(S3EncryptionKeyProvider.java:74)
	at io.aiven.kafka.tiered.storage.s3.S3ClientWrapper.uploadLogSegmentData(S3ClientWrapper.java:124)
	at io.aiven.kafka.tiered.storage.s3.S3RemoteStorageManager.copyLogSegmentData(S3RemoteStorageManager.java:77)
	at kafka.log.remote.ClassLoaderAwareRemoteStorageManager.$anonfun$copyLogSegmentData$1(ClassLoaderAwareRemoteStorageManager.scala:54)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at kafka.log.remote.ClassLoaderAwareRemoteStorageManager.withClassLoader(ClassLoaderAwareRemoteStorageManager.scala:34)
	at kafka.log.remote.ClassLoaderAwareRemoteStorageManager.copyLogSegmentData(ClassLoaderAwareRemoteStorageManager.scala:54)
	at kafka.log.remote.RemoteLogManager$RLMTask.$anonfun$copyLogSegmentsToRemote$8(RemoteLogManager.scala:456)
	at kafka.log.remote.RemoteLogManager$RLMTask.$anonfun$copyLogSegmentsToRemote$8$adapted(RemoteLogManager.scala:376)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.remote.RemoteLogManager$RLMTask.$anonfun$copyLogSegmentsToRemote$1(RemoteLogManager.scala:376)
	at kafka.log.remote.RemoteLogManager$RLMTask.$anonfun$copyLogSegmentsToRemote$1$adapted(RemoteLogManager.scala:351)
	at scala.Option.foreach(Option.scala:437)
	at kafka.log.remote.RemoteLogManager$RLMTask.copyLogSegmentsToRemote(RemoteLogManager.scala:351)
	at kafka.log.remote.RemoteLogManager$RLMTask.run(RemoteLogManager.scala:580)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```